tibiadata/tibiadata-api-go

- src/TibiaSpellsOverviewV3.go
- src/TibiaSpellsSpellV3.go
- src/webserver.go
This PR is the first attempt at a solution for https://github.com/TibiaData/tibiadata-api-go/issues/12.
Along with fixing the spell formula, I've also added in a fix for city names (specifically Ab'Dendriel).
> Sanitize certain data

- src/TibiaCharactersCharacterV3.go
- src/TibiaCreaturesCreatureV3.go
- src/webserver.go
removing some of the code smell. but there is more to go..
> Removing some code smell from SonarCloud

- src/TibiaHighscoresV3.go
- src/webserver.go
As the title says, I found a few small lint errors, this PR aims to fix that.
> clear lint errors

- src/TibiaCharactersCharacterV3.go
- src/TibiaCreaturesCreatureV3.go
- src/TibiaFansitesV3.go
- src/TibiaSpellsOverviewV3.go
- src/TibiaSpellsSpellV3.go
- src/TibiaWorldsOverviewV3.go
- src/TibiaWorldsWorldV3.go
- src/webserver.go
As per https://go.dev/doc/effective_go#switch, in go it is idiomatic to use switch cases over else if's. 
In this PR I aim to move all cases of else ifs that I found to be better suited with switch cases. 
I also saw that Tibia's website has a weird format for the `Account Status` and `Guild Membership` data, and you used `strings.Contains` for those. In case for it to be better suited with the switch case, I instead used an array of bytes (converted to a string) that exactly matches the output of Tibia's data and compare against that. 
Let me know what you think :)
> idiomatic go

- src/webserver.go
Currently `/highscores/world/:world` and `/highscores/world/:world/:category"` are incorrectly redirecting.
Instead of redirecting to `/highscores/world/:world/:category/:vocation`, they are redirecting to `/highscores/:world/:category/:vocation`.
> fix highscores endpoints

- src/TibiaCharactersCharacterV3.go
- src/TibiaFansitesV3.go
- src/TibiaGuildsGuildV3.go
- src/TibiaGuildsOverviewV3.go
- src/TibiaSpellsOverviewV3.go
- src/webserver.go
Today there are multiple ways of running _html.UnescapeString_.
This PR is replacing `html.UnescapeString` and `TibiadataUnescapeStringV3` with `TibiaDataSanitizeEscapedString`.
> Removing duplicate function

- src/TibiaCharactersCharacterV3.go
- src/TibiaCreaturesCreatureV3.go
- src/TibiaCreaturesOverviewV3.go
- src/TibiaFansitesV3.go
- src/TibiaGuildsGuildV3.go
- src/TibiaGuildsOverviewV3.go
- src/TibiaHighscoresV3.go
- src/TibiaKillstatisticsV3.go
- src/TibiaSpellsOverviewV3.go
- src/TibiaSpellsSpellV3.go
- src/TibiaWorldsOverviewV3.go
- src/TibiaWorldsWorldV3.go
- src/webserver.go
This PR adds code to detect `302 Found` with redirection to maintenance domain.
Clients will receive `503 Service Unavailable` including an error explaining why.
> Maintenance mode detection with error message return

- src/TibiaGuildsGuildV3.go
- src/TibiaGuildsOverviewV3.go
- removing log printing (accidentally added with #34)
- adding trim of guild description 
- using guild name based on html response (so we get correct upper and lower letters in name)
> Guilds name upper casing correction

- src/TibiaCharactersCharacterV3.go
- src/TibiaCreaturesCreatureV3.go
- src/TibiaCreaturesOverviewV3.go
- src/TibiaFansitesV3.go
- src/TibiaGuildsGuildV3.go
- src/TibiaGuildsOverviewV3.go
- src/TibiaHighscoresV3.go
- src/TibiaKillstatisticsV3.go
- src/TibiaSpellsOverviewV3.go
- src/TibiaSpellsSpellV3.go
- src/TibiaWorldsOverviewV3.go
- src/TibiaWorldsWorldV3.go
- src/webserver.go
- adding rate-limit detection on `403`, if there are too many requests being sent to upstream
- changing response error code when maintenance from `503` to `502` (rel #34)
> Adding rate-limit detection and status code switching

- src/TibiaCharactersCharacterV3_test.go
As per https://github.com/stretchr/testify we should use `assert.New(t)` instead of passing `t` many times.
This PR aims to do that.
> use new assert instead of passing t many times

- .github/workflows/codecov.yml
- go.mod
- go.sum
- src/TibiaCharactersCharacterV3_test.go
- src/TibiaDataUtils.go
- src/TibiaDataUtils_test.go
- src/webserver.go
> Handle timezone information during DateTime parsing

- .github/workflows/codecov.yml
- go.mod
- go.sum
- src/TibiaCharactersCharacterV3_test.go
- src/TibiaDataUtils.go
- src/TibiaDataUtils_test.go
- src/webserver.go
* Handle timezone information during DateTime parsing
* adjusting asserts to be UTC
* updating TibiadataDatetimeV3 with correct format
Fixes #42
> Handle timezone information during DateTime parsing (#46)

- src/TibiaDataUtils.go
- src/main.go
- src/webserver.go
Hi!
Just for organization purposes, I decided to split `webserver.go` into 3 differente files: `webserver.go`, `main.go` and `TibiaDataUtils.go`. (`TibiaDatautils.go` already existed, I just added more functions to it).
The reason for this is that the `main` function, as well as some utility functions were all in `webserver.go`. I just moved the functions already.
There is no logic change in this PR, it is only organization really.
The only "code change" I made was instead of keeping
```
// TibiaDataSanitizeNbspSpaceString func - replaces weird \u00A0 string to real space
func TibiaDataSanitizeNbspSpaceString(data string) string {
ret := strings.ReplaceAll(data, "\u00A0", " ")
return ret
}
```
I changed it to
```
// TibiaDataSanitizeNbspSpaceString func - replaces weird \u00A0 string to …
```
> clean up webserver.go

- .gitignore
- README.md
- src/HousesMapping.go
- src/TibiaDataUtils.go
- src/TibiaHousesHouseV3.go
- src/TibiaHousesOverviewV3.go
- src/main.go
- src/webserver.go
This feature includes following endpoints:
- GET `/v3/houses/world/:world/house/:houseid`
- GET `/v3/houses/world/:world/town/:town`
> Feature: Tibia Houses endpoints

- src/webserver.go
As of right now, we don't have a graceful shutdown for the webserver, this PR aims to implement it.
> implement graceful shutdown

- src/webserver.go
Instead of failing on non-existent endpoints, let's return a 404 instead.
> implement 404 page not found

- src/webserver.go
- src/webserver_test.go
Switching to http package status codes instead of plain integers
- `200` to `http.StatusOK`
- `404` to `http.StatusNotFound`
> Switching to http status codes

- src/TibiaCharactersCharacterV3.go
- src/TibiaCharactersCharacterV3_test.go
Cleaning up in characters deaths:
- removing TruncatedDeaths
- switching from object to array of object
> Cleanup of characters deathlist

- src/TibiaDataUtils.go
Environment vars functions logic fix (originally from https://github.com/TibiaData/tibiadata-api-go/pull/86)
- `isEnvExist` and `getEnv` are being simplified and logic is being fixed
Code adjustment as in https://github.com/TibiaData/tibiadata-api-assets/pull/6
> Environment function logic fix

- src/TibiaCharactersCharacterV3.go
- src/TibiaDataUtils.go
- src/TibiaGuildsGuildV3.go
- src/TibiaHousesHouseV3.go
- src/TibiaHousesOverviewV3.go
- src/TibiaNewslistV3.go
- src/TibiaWorldsWorldV3.go
- change `TibiaDataSanitizeNbspSpaceString` to `TibiaDataSanitizeStrings`
- running `TibiaDataSanitizeEscapedString` in `TibiaDataSanitizeStrings`
fix #103
> fix encoding of apostrophes in multiple places

- src/TibiaGuildsGuildV3.go
- checking if `GuildDescription` starts with foundation string and if that's the case, setting description string to be empty
fix #93
> fix guild description to contain guild details

- src/TibiaHousesOverviewV3.go
- src/TibiaHousesOverviewV3_test.go
finished is an auction-related value, so should be inside auction struct instead.
adjusts #115
ref #114
> moving finished bool into auction struct

- .github/workflows/codecov.yml
- .github/workflows/documentation.yml
- go.mod
- go.sum
It looks like the project has been already migrated to 1.18 but go.mod still specifies 1.17. :)
> change go version in go.mod

- src/TibiaCharactersCharacterV3.go
This fixes " (traded)" string appearing in account characters info.
An example of this bad behavior can be currently observed for this character https://api.tibiadata.com/v3/character/Trafnar
> Fix " (traded)" string appearing in account characters info

- .github/workflows/build.yml
Removing the leading **v** in container image tag so that it's correct [semver](https://semver.org) versioning.
This means that users that are using a specific version in their docker-compose (or other) need to remove the leading **v**.
For the upcoming version _3.3_ the tag would change from `v3.3` to `3.3`, looking like this in the docker-compose file:
```yaml
image: ghcr.io/tibiadata/tibiadata-api-go:3.3
```
> Removing **v** in container image tag

- src/TibiaBoostableBossesOverviewV3.go
- src/TibiaCreaturesOverviewV3.go
This fixes an issue that happened when Goshnar's Cruelty was the boosted boss:
> Fix handling of special characters in boosted boss/creature name

- src/webserver.go
Most worlds only have 20 pages, but some worlds (where many have same type of highscores), the amount of pages can be higher. Setting max to 23 instead of 21.
fix #167
> Adjusting highscore span to support page up to 23

- src/TibiaDataUtils.go
- src/TibiaHighscoresV3.go
- src/webserver.go
_strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)_
> replacing strings.Title with cases.Title

- src/validation/limits.go
- src/validation/validation_test.go
Older characters can have a longer length than 14.
Example char:
- Crocodilo'Dundee
fix #193
> extending character name max length

- src/webserver.go
func tibiaHighscores had a hard limit of 30 pages, this hard limit should not be there because there are times where tibia's highscore has more than 30 pages,
for example highscore of magiclevel of knights only on Antica.
fixes https://github.com/TibiaData/tibiadata-api-go/issues/209
> fix highscores pages bug

- src/TibiaCharactersCharacter.go
Instead of iterating over a slice, use a switch case on containsCreaturesWithOf.
This is faster even on the best case scenario for the slice, which is searching for `acolyte of darkness` (first item in the slice).
> TibiaCharactersCharacter: use switch case for containsCreaturesWithOf

- src/TibiaCharactersCharacter.go
- src/TibiaCharactersCharacter_test.go
- src/static/testdata/characters/Orca Kaoksh.html
> fix character deaths where timestamp contains CEST

- src/TibiaCharactersCharacter.go
- src/TibiaCreaturesCreature.go
- src/TibiaCreaturesOverview.go
- src/TibiaFansites.go
- src/TibiaGuildsGuild.go
- src/TibiaGuildsOverview.go
- src/TibiaHighscores.go
- src/TibiaHousesHouse.go
- src/TibiaHousesOverview.go
- src/TibiaKillstatistics.go
- src/TibiaNews.go
- src/TibiaNewslist.go
- src/TibiaSpellsOverview.go
- src/TibiaSpellsSpell.go
- src/TibiaWorldsOverview.go
- src/TibiaWorldsWorld.go
- src/main.go
- src/tibiamapping/tibiamapping.go
- src/validation/tibia.go
- src/validation/validation.go
- src/validation/validation_test.go
- src/webserver.go
Most parsers were returning a pointer to a struct type, resulting in unnecessary heap allocations.
This PR changes all parsers to return the struct they build itself, instead of a pointer to them.
> all: reduce heap allocations

- src/validation/limits.go
- src/validation/validation_test.go
> fix max length of character name

- src/TibiaNewsV3.go
- src/TibiaNewsV3_test.go
- testdata/news/archive/504.html
Fixes https://github.com/TibiaData/tibiadata-api-go/issues/290 for v3
> fix not parsing all news ticker properly

- src/validation/tibia.go
- src/validation/tibia_test.go
- src/webserver.go
Fixes https://github.com/TibiaData/tibiadata-api-go/issues/294
> validation: replace '+' with ' ' in TownExists

- src/validation/errors.go
- src/webserver.go
- src/webserver_test.go
_see #300 for initial issue description._
> webserver/validation: improve error handling on non OK status codes

- src/validation/tibia.go
- src/validation/validation_test.go
fixes https://github.com/TibiaData/tibiadata-api-go/issues/305
> validation: consider +, - and ' as a valid separators for character name words

- Dockerfile
- using alpine specific version instead of latest
- running container with nonroot user
> Update Dockerfile to specific version and use of nonroot user

- src/TibiaCharactersCharacter.go
- src/TibiaCharactersCharacter_test.go
- src/static/testdata/characters/Mieluffy.html
fixes https://github.com/TibiaData/tibiadata-api-go/issues/318
> fix: properly parse players with 'and' in their names

- Dockerfile
> fix permission issues with Dockerfile nonroot implementation

- src/TibiaCharactersCharacter.go
- src/TibiaCharactersCharacter_test.go
- src/static/testdata/characters/Ninth Dimension.html
> fix character killer parser by rewrite of death parsing logic

- .github/workflows/build.yml
- .github/workflows/codecov.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/documentation.yml
- README.md
> ci: rewrite GitHub action workflows

- src/TibiaWorldsWorld.go
- src/TibiaWorldsWorld_test.go
- src/static/testdata/worlds/world/Oceanis.html
> new world record_date field omit if empty

- README.md
- src/main.go
- src/validation/errors.go
- src/validation/tibia.go
- src/validation/validation_test.go
- src/webserver.go
> feat: add restriction mode

- Dockerfile
- Reduce the amount of consecutive RUN instructions [docker:S7031](https://sonarcloud.io/organizations/tibiadata/rules?open=docker%3AS7031&rule_key=docker%3AS7031)
- Too long RUN instruction should be split into multiple lines [docker:S7020](https://sonarcloud.io/organizations/tibiadata/rules?open=docker%3AS7020&rule_key=docker%3AS7020)
_Suggestions by SonarCloud_
> decrease Dockerfile layers

- README.md
- src/webserver.go
- src/webserver_test.go
This is for tools to test the container (like our testing of helm-chart in [TibiaData/tibiadata-helm-charts](https://github.com/TibiaData/tibiadata-helm-charts)) to not fail.
```plain
HTTP/1.1 404 Not Found
```
> feat: add root-endpoint to container

- src/validation/tibia.go
- src/validation/validation_test.go
> fix: character name can contain comma

- src/TibiaNewslist.go
- src/main.go
- src/main_test.go
- src/webserver.go
This pull request includes several changes to improve the configuration and initialization of the TibiaData API, as well as enhancements to the user agent generation. The most important changes include adding support for specifying the protocol used by the TibiaData API, refactoring the initialization process, and updating the user agent generator to include protocol information.
Configuration enhancements:
* [`src/main.go`](diffhunk://#diff-9e185f29fa355d7dd8fdd9c9ff1d0723b85206aa7d37c4eec93997005dc291ebL23-R25): Added a new configuration variable `TibiaDataProtocol` to allow specifying the protocol used by the TibiaData API. This can be overridden by the environment variable `TIBIADATA_PROTOCOL`.
* [`src/main.go`](diffhunk://#diff-9e185f29fa355d7dd8fdd9c9ff1d0723b85206aa7d37c4eec93997005 …
> fix: url_api field format on news endpoints

- src/TibiaCharactersCharacter.go
- src/TibiaCharactersCharacter_test.go
- src/static/testdata/characters/Nannorka.html
This pull request includes several changes to the `TibiaCharactersCharacter.go` file, focusing on improving the handling of character death data and adding a new test case. Key changes include adding an `omitempty` tag to the `Level` field, improving string sanitization, and adding logic to handle deaths with assists more accurately. Additionally, a new test case has been added to validate these changes.
Improvements to character death data handling:
* [`src/TibiaCharactersCharacter.go`](diffhunk://#diff-e7e958291215ebb01a9df1c22d6e8ecd866edc0d2c411a490dc590d0d626214dL79-R79): Added `omitempty` tag to the `Level` field in the `Deaths` struct to omit the field when it is zero.
* [`src/TibiaCharactersCharacter.go`](diffhunk://#diff-e7e958291215ebb01a9df1c22d6e8ecd866edc0d2c411a490dc590d0d626 …
> fix: character-death parsing when only being assisted

- src/TibiaCharactersCharacter.go
- src/TibiaCharactersCharacter_test.go
- src/static/testdata/characters/Akayev.html
This pull request includes changes to the `src/TibiaCharactersCharacter.go` and `src/TibiaCharactersCharacter_test.go` files. The changes enhance the character death handling and add a new test case.
Enhancements to character death handling:
* [`src/TibiaCharactersCharacter.go`](diffhunk://#diff-e7e958291215ebb01a9df1c22d6e8ecd866edc0d2c411a490dc590d0d626214dL378-R378): Modified the `Character Deaths` case to also handle `Character Deaths (Last 30 Days)`.
New test case addition:
* [`src/TibiaCharactersCharacter_test.go`](diffhunk://#diff-9ffccceb03986b6056631db171cb6cb57cbdc8e83ac6e495e3b0dc96c65f9a18R4000-R4077): Added a new test function `TestNumber17` to validate the character death data for a specific character, including detailed checks on the death records.
fix #462
> fix: character death html header change

- src/TibiaCharactersCharacter.go
This pull request includes a minor change to the `src/TibiaCharactersCharacter.go` file. The change involves modifying the `DeathsTruncated` field in the `Character` struct to be optional in the JSON output.
* [`src/TibiaCharactersCharacter.go`](diffhunk://#diff-e7e958291215ebb01a9df1c22d6e8ecd866edc0d2c411a490dc590d0d626214dL111-R111): Changed the `DeathsTruncated` field in the `Character` struct to include the `omitempty` tag, making it optional in the JSON output.
> fix: omit character deaths_truncated if false

- src/TibiaDataUtils.go
- src/TibiaDataUtils_test.go
This pull request updates the string escaping logic in `TibiaDataQueryEscapeString` and its associated tests to improve Unicode handling and simplify encoding. The main change is the removal of the conversion to Latin-1 encoding, allowing proper UTF-8 percent-encoding for non-ASCII characters.
String escaping and encoding improvements:
* Removed the conversion to Latin-1 encoding in `TibiaDataQueryEscapeString`, so strings are now percent-encoded directly in UTF-8, which is the standard for URLs.
* Updated the tests in `TestEscaper` to expect UTF-8 percent-encoded output for non-ASCII characters, and added a new test case for the string `Näurin`.
fix #470 
close #471
> fix: remove iso-encoding for umlaut issue

- .github/workflows/build.yml
This pull request makes significant improvements to the GitHub Actions workflow for building and publishing Docker images. The main changes include refactoring the build process to use a matrix strategy for multi-architecture builds, introducing a separate manifest job for aggregating per-architecture images, and enhancing image signing and attestation for better security and provenance. Additionally, downstream workflows now correctly reference the manifest job outputs for image digests and versions.
**Workflow refactor and multi-arch support:**
* The `build` job now uses a matrix strategy to build images for multiple architectures (`linux/amd64`, `linux/arm64`, `linux/arm/v7`), each on dedicated runners. This enables true multi-arch support and parallelizes the build process. …
> feat(ci): use multiple runners for build

- .github/workflows/build.yml
- .github/workflows/dockerhub.yml
This pull request makes a minor update to the GitHub Actions workflow by changing how the DockerHub username is referenced. The workflow now uses GitHub Actions variables instead of secrets for the DockerHub username in all relevant steps.
rel #508
> fix(ci): use dockerhub variable instead

- .github/workflows/codecov.yml
- README.md
This pull request makes minor updates to ensure consistency in repository naming for Codecov integration. The Codecov badge and the workflow configuration have both been updated to use the correct, case-sensitive repository slug.
> fix(ci): specify slug for codecov
