tibiadata/tibiadata-api-go

README.md

- add badge to readme on GitHub Actions last build
- adding section in readme on how to run docker image right away

update of readme with badge and deployment information

---

.github/workflows/build.yml
Dockerfile
src/webserver.go

- release from unknown to -
- adding step to configure build info
- adding initializer function
rel #6

Updating building and release process

---

src/TibiaFansitesV3.go

- using for loop to scan two fansite-sections

shrink of TibiaFansitesV3.go

---

.github/workflows/build.yml
README.md

- adding edge docker image tag for image based on main branch
- updating readme with changed docker tag
- only doing build when certain paths are changed

Updating build workflow with enhancements

---

src/webserver.go

Wrap response body in an io.Reader that knows how to convert between charsets
Avoid needlessly allocating extra strings and ints

Fix decoding issues and save some allocations

---

.github/workflows/build.yml
src/TibiaCharactersCharacterV3.go
src/TibiaCreaturesCreatureV3.go
src/TibiaCreaturesOverviewV3.go
src/TibiaHighscoresV3.go
src/TibiaKillstatisticsV3.go
src/TibiaSpellsOverviewV3.go
src/TibiaSpellsSpellV3.go
src/TibiaWorldsWorldV3.go
src/webserver.go

Continue working on decoding function.
Ref #15 
Fix #13

Fix decoding decoding issues

---

src/TibiaHighscoresV3.go
src/TibiaSpellsOverviewV3.go
src/webserver.go

Moving vocation logic to separate function, to be able to sanitize the input.

Moving vocation logic to separate function

---

README.md
src/TibiaCharactersCharacterV3.go
src/TibiaGuildsGuildV3.go
src/TibiaGuildsOverviewV3.go
src/webserver.go

- endpoint to list all guilds of a certain world:
`/guilds/world/:world`
- endpoint to get more details about a guild:
`/guilds/guild/:guild`

Addition of two guild endpoints

---

src/TibiaGuildsOverviewV3.go

Refactor to use pure goquery and no manual regex.

---

src/TibiaCharactersCharacterV3.go
src/TibiaCreaturesCreatureV3.go
src/TibiaCreaturesOverviewV3.go
src/TibiaFansitesV3.go
src/TibiaGuildsGuildV3.go
src/TibiaGuildsOverviewV3.go
src/TibiaHighscoresV3.go
src/TibiaKillstatisticsV3.go
src/TibiaSpellsOverviewV3.go
src/TibiaSpellsSpellV3.go
src/TibiaWorldsOverviewV3.go
src/TibiaWorldsWorldV3.go
src/webserver.go

- adds possibility to use POST and not only GET
- changes way of calling the _TibiadataHTMLDataCollectorV3_ with a struct
- adds trace information on requests for detailed measuring

Enhance data collection and debugging information

---

src/webserver.go

Just a couple of small clean ups.

clean up a few utility funcs

---

src/webserver.go

- switching env from `TIBIADATA_UA_HOSTNAME` to `TIBIADATA_HOST`

Adding TIBIADATA_HOST env

---

.github/workflows/sonarcloud.yml
README.md
sonar-project.properties

Adding SonarCloud code coverage analyzing

---

README.md
src/TibiaDataUtils.go
src/TibiaNewsV3.go
src/TibiaNewslistV3.go
src/webserver.go

This feature includes following endpoints:
- GET `/v3/news/archive`
- GET `/v3/news/archive/:days`
- GET `/v3/news/id/:news_id`
- GET `/v3/news/latest`
- GET `/v3/news/newsticker`

Feature: Tibia News endpoints

---

src/TibiaCharactersCharacterV3.go

fix: adding if to prevent panic due to regex

---

.github/workflows/build.yml
CHANGELOG.md
Dockerfile
src/HousesMapping.go
src/TibiaCharactersCharacterV3.go
src/TibiaCreaturesCreatureV3.go
src/TibiaCreaturesOverviewV3.go
src/TibiaDataUtils.go
src/TibiaDataUtils_test.go
src/TibiaFansitesV3.go
src/TibiaGuildsGuildV3.go
src/TibiaGuildsOverviewV3.go
src/TibiaHighscoresV3.go
src/TibiaHousesHouseV3.go
src/TibiaHousesOverviewV3.go
src/TibiaHousesOverviewV3_test.go
src/TibiaKillstatisticsV3.go
src/TibiaNewsV3.go
src/TibiaNewslistV3.go
src/TibiaNewslistV3_test.go
src/TibiaSpellsOverviewV3.go
src/TibiaSpellsSpellV3.go
src/TibiaWorldsOverviewV3.go
src/TibiaWorldsWorldV3.go
src/main.go
src/webserver.go
src/webserver_test.go

Consistency changes (originally from #86)
- changed all Tibiadata names to TibiaData for consistency

renaming Tibiadata to TibiaData

---

src/HousesMapping.go
src/TibiaHousesHouseV3.go
src/TibiaHousesHouseV3_test.go

removing injection of houseType from assets

---

src/TibiaCharactersCharacterV3.go

adding sanitize of nsbp string in death section of players

---

src/TibiaCharactersCharacterV3.go

adding sanitize of nbsp string in death reason of players

---

src/TibiaHousesHouseV3.go

fixing regex to handle one bed in house

---

Dockerfile

which should shorten build time..

updating `go build` step in dockerfile

---

src/TibiaGuildsGuildV3.go

Fix parsing issue when guild description contains founded string

---

src/HighscoreCategory.go
src/HighscoreCategory_test.go
src/TibiaHighscoresV3.go
src/webserver.go

The latest summer update introduced a new `bosspoints` category to high scores.

Expanded HighscoreCategory with new boss points

---

src/main.go

Adding proxy protocol support to replace default https

---

src/TibiaHighscoresV3.go

- replacing `&raquo;` with `.*`
rel #164, rel #162

fix HighscoresPageRegex regex

---

src/TibiaCreaturesCreatureV3.go
src/TibiaCreaturesCreatureV3_test.go
testdata/creatures/creature/centipede.html
testdata/creatures/creature/hunter.html
testdata/creatures/creature/skunk.html

Some monsters such as cobra and centipede can be summoned but not convinced. This has been the case for several years to prevent pvp abuse.

Fix issue parsing summon mana cost

---

src/TibiaCharactersCharacterV3.go
src/TibiaCharactersCharacterV3_test.go
testdata/characters/Luminals.html

- fixing account badge parsing
- adding testdata for account badges
fix #177

fixing account badge parsing

---

src/TibiaCreaturesCreatureV3.go
src/TibiaCreaturesCreatureV3_test.go
src/static/testdata/creatures/creature/lava lurkers.html

add parsing of healed by damage for creatures

---

src/TibiaCharactersCharacter.go
src/TibiaCharactersCharacter_test.go
src/static/testdata/characters/Nocna Furia.html

fix character title that contains Grade

---

src/TIbiaDataDocsV3.go
src/TibiaCharactersCharacter.go
src/TibiaCharactersCharacter_test.go

Fixes https://github.com/TibiaData/tibiadata-api-go/issues/273

Truncated deaths

---

src/validation/limits.go
src/validation/validation_test.go

min length inside name to be 1
fix #287

fix shorter character names

---

src/webserver.go

Fixes https://github.com/TibiaData/tibiadata-api-go/issues/296

tibiaHousesOverview: format Ab'Dendriel properly

---

.github/workflows/codecov.yml

switch from custom proxy to tailscale vpn

---

src/TibiaBoostableBossesOverview.go
src/TibiaBoostableBossesOverview_test.go
src/static/testdata/boostablebosses/boostablebosses.html

fix: empty boostablebosses list

---

src/TibiaGuildsGuild.go
src/TibiaGuildsGuild_test.go
src/static/testdata/guilds/guild/True Players.html

fix: change guild rank length check

---

src/TibiaCharactersCharacter.go
src/TibiaCharactersCharacter_test.go
src/static/testdata/characters/Sergiozk.html
src/static/testdata/characters/Sir Dumbas.html

This pull request includes several changes to the `src/TibiaCharactersCharacter.go` file and its associated test file `src/TibiaCharactersCharacter_test.go`. The changes primarily focus on improving string handling, adding new test cases, and updating existing test cases to match the new string handling logic.
* Added imports for `unicode` and `unicode/utf8` to handle string prefixes and character cases. (`src/TibiaCharactersCharacter.go`)
* Enhanced the `TibiaDataParseKiller` function to remove prefixes like "and", "a", and "an" from data strings and handle lowercase characters. (`src/TibiaCharactersCharacter.go`)
* Updated multiple test cases in `TestNumber4` to remove prefixes like "a" and "an" from creature names in death records. (`src/TibiaCharactersCharacter_test.go`) …

fix: improve character death parsing and removing creature prefix
